### ISSUE TITLE
关于baseline模型

### ISSUE THREAD

**Issue by fanyangfanyang** [ymcui/cmrc2019#1]
这里提供的baseline模型似乎是用来处理SQuAD任务的，而不是用来处理cmrc2019评测中的句子级完形填空任务的。

**Comment by ymcui** [comment]
基线系统由评测委员会中的一位同学编写，他并没有修改原run_squad.py中的双指针输出（start/end)。事实上如果想更加契合本任务，只需输出一个指针位置即可。我们不对任务的输出形式进行限制，选手可自行决定以何种形式输出。

**Comment by ymcui** [comment]
代码更新后会重新上传到该目录，谢谢报告。
