### ISSUE TITLE
run_cmrc2019_baseline.py: error: unrecognized arguments: --bert_model bert-base-chinese

### ISSUE THREAD

**Issue by libertatis** [ymcui/cmrc2019#2]
我按照Step1和Step2做好后，运行Training的命令，出现了不能识别bert_model参数的问题。我在[run_cmrc2019_baseline.py](https://github.com/ymcui/cmrc2019/blob/master/baseline/run_cmrc2019_baseline.py)这个文件里，似乎也没能找到bert_model这个参数在哪儿。请问这里参数是不是给错了呢？
PS：在Step2中，我的做法是：
1）首先，下载BERT-BASE, Chinese预训练模型[chinese_L-12_H-768_A-12.zip](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip)，解压后得到：bert_config.json, bert_model.ckpt.data-00000-of-00001, bert_model.ckpt.index  bert_model.ckpt.meta, vocab.txt 五个文件。
2）然后，clone [pytorch-pretrained-BERT](https://github.com/huggingface/pytorch-pretrained-BERT)项目，
3）最后运行如下命令：
`
export BERT_BASE_DIR=/path/to/bert/chinese_L-12_H-768_A-12

pytorch_pretrained_bert convert_tf_checkpoint_to_pytorch \
  $BERT_BASE_DIR/bert_model.ckpt \
  $BERT_BASE_DIR/bert_config.json \
  $BERT_BASE_DIR/pytorch_model.bin
`

4）生成pytorch_model.bin后，我将bert_config.json，pytorch_model.bin，vocab.txt三个文件放在本项目的cmrc2019/baseline/bert_weights_chinese路径下。路径应该是没有问题的。
5）运行Training命令：

`
python run_cmrc2019_baseline.py \
	--bert_model bert-base-chinese \
	--vocab_file ./bert_weights_chinese/vocab.txt \
	--bert_config_file ./bert_weights_chinese/bert_config.json \
	--init_checkpoint ./bert_weights_chinese/pytorch_model.bin \
	--do_train \
	--do_predict \
	--train_file cmrc2019_train.json \
	--predict_file cmrc2019_trial.json \
	--train_batch_size 24 \
	--learning_rate 2e-5 \
	--num_train_epochs 3.0 \
	--max_seq_length 512 \
	--output_dir ./output_model
`
出现了如下问题：
run_cmrc2019_baseline.py: error: unrecognized arguments: --bert_model bert-base-chinese
请问是我的预训练模型下载错了吗（不应该呀）？还是参数给错了呢？

**Comment by ymcui** [comment]
感谢告知，忽略`--bert_model`即可。
